### PR TITLE
DirectShow usb webcam improvements.

### PR DESCRIPTION
**Pull request by anguzo**
Engine: Add enumerator for usb webcams.
Demuxer: Add support for dshow device parameters.
FlyleafPlayer (WPF Control): Add "Open Device" menu.

Issues:
1. IMPORTANT! Usb webcam has noticeable latency. Setting MaxLatency to 1 and then to 0 fixes this. What is the reason?
2. Flyleaf does not play NV12. NV12 throws -5 on avformat_open_input.  Maybe there are other not supported webcam video formats?
3. Should ffmpeg.av_dict_free(ref AVDictionary*) be used to dispose of avopt in Demuxer?

### CODE REVIEW

**Comment by SuRGeoNix** [comment]
That looks great @anguzo, I just think we should keep audio devices (even just the name to show what is available to be combined with the video). It would be also great if we could avoid extra NuGet packages. Gdigrab could be added as well for desktop/Title, possible other devices in the future eg. decklink with video_input=hdmi/usb etc.) For the issues:-

1) Do you have default (0) initially? Does this happen generally with other formats? I will need to reproduce it (maybe trace log would help)
2) -5 is I/O Error probably means that pix fmt is not supported. You could try that with ffplay and see. Otherwise you might try different FFmpeg libraries?
3) Yes, we could just print the returned entries that failed (not found) and then free it (I missed that)

**Comment by SuRGeoNix** [comment]
I will review the NuGet packages no worries. I think System.Management will be useful anyways for other things as I remember. For the query string I would be there is another way with System.Http maybe or something. I didn't pull it yet to review it so I will do some testing with cameras as well and I will let you know about the parameters.

**Comment by anguzo** [comment]
System.Management is not the only way to achieve webcam observing,  check my repo https://github.com/anguzo/mf-video-device-enumerator. Also I believe LibUsbDotNet can achieve this.

**Comment by SuRGeoNix** [comment]
So Vortice couldn't enumerate those, right?

**Comment by anguzo** [comment]
Not to my knowing. Windows Core Audio API IMMNotificationClient is for audio endpoint devices. I think nor DirectShow API nor Media Foundation API provide this functionality for webcams. 
I also thought about possible ways to achieve format info gathering using FFmpeg.AutoGen since -list_devices and -list_options get the needed information from webcams, but I think it is only possible by subscribing to logging which provides this info and parsing logs.

**Comment by SuRGeoNix** [comment]
@anguzo Just notice a critical issue with this... it does not separate the options with the Url parameters. https://ffmpeg.org/ffmpeg-devices.html

For example this one will not work device://gdigrab?desktop

You expect video parameter always which is wrong (I will look more in to it)

**Comment by SuRGeoNix** [comment]
After reviewing this further I'm afraid that Cap devices should probably removed from FlyleafLib. This should be in higher level (directly from the app). Engine shouldn't waste time for enumeration (as it does not require them) and it shouldn't add usb event listener either. Maybe on demand but again, this can be implemented on higher level. Maybe just expose the Cap devices from Vortice when requested. Let me know your thought but I'm afraid I will remove them.

**Comment by anguzo** [comment]
Makes sense. Basically audio engine is also redundant in that sense. Especially if in some next Windows 11 version an audio control panel similar to EarTrumpet will be added. Or user can you use EarTrumpet anyway. Or maybe those can moved to separate plugin(though this feels redundant)?

**Comment by SuRGeoNix** [comment]
Not sure yet. From the other hand, it shouldn't really have performance issues a a simple enumeration. I'm doing some clean-up and I will see. I was thinking to leave it as it is a nice enhancement and just don't include the USB watcher but expose the CapDevices so they can updated from the App level. Instead of ManagementEventWatcher I think it should be replaced with a more generic event for CapDevices (I was looking in to it https://learn.microsoft.com/en-us/windows/win32/api/cfgmgr32/nf-cfgmgr32-cm_register_notification).

**Comment by anguzo** [comment]
Updating video devices explicitly is viable option. Maybe use ConcurrentDictionary<device.id, device> or just <device.id, device.friendlyName> then there is no need to Clear and Re-Add all devices to ObservableCollection.

I also put up somewhat more concise implementation of IMMNotificationClient using Vortice.
https://github.com/anguzo/mf-audio-device-enumerator/blob/master/MFAudioDeviceEnumeratorVorticeWpfApp/AudioManager/AudioDeviceManager/AudioDeviceManager.cs
Instead of refreshing all devices on each event it removes, adds, updates default device only on corresponding event. I also made sure that events are not called more than needed and contents of observable collection are backed by ConcurrentDictionary.
I am not sure, but maybe IMMNotificationClient DefaultChanged would still be needed to ensure right playback device?

**Comment by SuRGeoNix** [comment]
So far I did removed the USB watcher but I left open the RefreshDevices so if the app want to update them. I moved the menu's under Audio/Video. I've added audio devices as well (eg. open a microphone).

**Comment by anguzo** [comment]
LONG STORY SHORT

Setting MaxLatency to 0 ms does not update Player.MinBufferDuration and Demuxer.BufferDuration. When I set MinBufferDuration to 0 in config instead of MaxLatency there is no delay or lag when playing USB camera. Setting MaxLatency to 1 ms during runtime updates MinBufferDuration to 10000 ticks, but then still some frames are dropped(because of screamer logic or this MinBufferDuration value?), so MaxLatency must be set back to 0.

Overall there was just some confusing logic, setting MinBufferDuration solves this problem. Maybe just if MaxLatency set to 0 ticks(as it is by default) then MinBufferDuration and BufferDuration must be 0? I am not sure how it corresponds with other logic.

```
set
{
    if (value < 0)
        value = 0;

    if (!Set(ref _MaxLatency, value)) return;

    if (value == 0)
    {
        if (player != null)
            player.Speed = 1;

        return;
    }

    // Large max buffer so we ensure the actual latency distance
    if (config != null && config.Demuxer.BufferDuration < value * 2)
        config.Demuxer.BufferDuration = value * 2;

    // Small min buffer to avoid enabling latency speed directly
    if (_MinBufferDuration > value / 10)
        MinBufferDuration = value / 10;
}
```

**Pull request merged**
