### PR TITLE
Add subtitle format plugin

### PR DESCRIPTION
**Pull request by afunc233**
This is my idea ~~

### CODE REVIEW

**Comment by afunc233** [comment]
Now I know your Consider ~

**Comment by afunc233** [comment]
now one subtitles frame once call plugin

**Comment by SuRGeoNix** [comment]
Nice, I will review it later, one more thing to consider is a bool parameter (e.g. e.Handled) to avoid using more than one parsers (not sure need to see what you want to do first)

**Comment by SuRGeoNix** [comment]
Didn't review it yet but I didn't mean this. I guess you added my old code as a new default plugin for parsing subtitles. So when you add another one (your custom) plugin does not be affected by default one? Should both of them parse the subs or just one?

**Comment by afunc233** [comment]
just one plugin effective at same time

**Comment by afunc233** [comment]
just one plugin effective at same time

**Comment by SuRGeoNix** [comment]
Thanks once again for the PR @afunc233 

I did few changes for performance and clean up. There is no point to have multiple plugins (and search for plugins on each decode) so I transfer this to Config.Subtitles.Parser (as an Action). Let me know if that's ok with you.

Check https://github.com/SuRGeoNix/Flyleaf/commit/8c3998f34f21f5e8a8858ea5b6dd9ca81f471994

**Comment by afunc233** [comment]
it's better than me , all i did just find a way to intervene SubtitlesFrame

**Pull request merged**
