### PR TITLE
Fix jitter when dragging windows on some devices

### PR DESCRIPTION
**Pull request by afunc233**
GIF 2022-9-27 11-09-38

### CODE REVIEW

**Comment by SuRGeoNix** [comment]
@afunc233 Thanks for the PR. This seems related to #59

Can you help me reproduce it so I can review this, does this happen because of the windows version?
TBH, I don't feel comfortable adding dpi requests and win API on every mouse down/move call. There must be a better way to implement this. Here some interesting posts on stackoverflow:-

https://stackoverflow.com/questions/58054021/how-to-handle-sendinput-mouse-movement-with-windows-scaling
https://stackoverflow.com/questions/13228185/how-to-configure-an-app-to-run-correctly-on-a-machine-with-a-high-dpi-setting-e
https://stackoverflow.com/questions/4226740/how-do-i-get-the-current-mouse-screen-coordinates-in-wpf

**Comment by afunc233** [comment]
@SuRGeoNix  It seems to be related to the screen resolution ，maybe the resolution exceeds 1920*1080 will appear ，and I first find this is on the Microsoft Surface devices it's 2880*1920 , But on my devices it's 2840*2160 not find this

**Comment by afunc233** [comment]
i was wrong , main reason is dpi 
image

@SuRGeoNix

**Comment by afunc233** [comment]
> i was wrong , main reason is dpi image
> 
> @SuRGeoNix

if there is 175% ,it vibrates slightly.
200% , particularly obvious.
250% ~ 350%, the window flash past.

**Comment by afunc233** [comment]
new commit has remove dpi requests and win API on every mouse down/move call. @SuRGeoNix

**Comment by SuRGeoNix** [comment]
I could notice it at my max (175%) dpi. Might be other places that dpi affects Flyleaf, let me know if you come across with something.

**Comment by afunc233** [comment]
thx your project ! it‘s best solution for  WPF with play video !

**Pull request merged**
