### PR TITLE
Public setter for PreventAborts

### PR DESCRIPTION
**Pull request by robvdpol**

### CODE REVIEW

**Comment by SuRGeoNix** [comment]
Oops, thanks. Had some conflicts with my local so I just push it with my changes. By the way, I've added also the audio device selection that you wanted. Hope soon will be ready for the first actual release  🚀

**Comment by robvdpol** [comment]
Cool, thank you.

By the way, I would like to have some events on Player such as TimeChanged, DurationChanged, StatusChanged (maybe you can come up with some more). This would really simplify things on my end.

Thanks,
Rob

________________________________
Van: John Stamatakis ***@***.***>
Verzonden: donderdag 22 april 2021 17:11
Aan: SuRGeoNix/Flyleaf ***@***.***>
CC: Rob ***@***.***>; Author ***@***.***>
Onderwerp: Re: [SuRGeoNix/Flyleaf] Public setter for PreventAborts (#28)


Oops, thanks. Had some conflicts with my local so I just push it with my changes. By the way, I've added also the audio device selection that you wanted. Hope soon will be ready for the first actual release 🚀

**Comment by SuRGeoNix** [comment]
You know that I don't like Invokes 🤣 (Especially within .NET's threadpool)

My point is, or you will get the propertychanged or the event but not both. I'm think that the property changed is better XAML wise (?)

**Comment by robvdpol** [comment]
Ah, I could get by with the PropertyChanged for now, it should work fine ;)

**Comment by SuRGeoNix** [comment]
Sorry , but I hope you understand that it has to be coded in a general purpose. In any case, probably you will come up with some issues I guess with those. Eg. with duration, it doesn't raise propertychanged. The initial idea was that a lot of attributes will change whether you create a new Session, probably the best thing would be to raise(nulls) in your view models to get the updates generally after opencompleted (the only event!).

Have a look and let me know how it goes and what do you suggest ;)

**Pull request closed without merging**
