### PR TITLE
Auto resizing subtitle text font size and thickness

### PR DESCRIPTION
**Pull request by Brandon689**
Now the text will scale with window instead of staying large and so will stroke thickness. Also text clipping at edges which rarely happens should be fixed.

### CODE REVIEW

**Comment by SuRGeoNix** [comment]
Thanks @Brandon689, please check my changes and let me know what you think. I will need to add the option (for the Config/Settings) to choose whether you want the auto resize or not

**Comment by Brandon689** [comment]
That's good, will you add config setting for the stroke thickness, I had trouble also with dependency properties because they are not initially set. I think for normal viewing conditions stroke thickness of 3 is good, at least on my 2560 X 1440 monitor. Then on smaller window it needs to taper to 1.

I looked at v2, I'm surprised you managed to get DirectWrite to work, I couldn't. But it doesn't have a outline, not sure how hard that is to implement.

**Comment by SuRGeoNix** [comment]
I've included stroke in UIConfig (SubsStrokeThickness) you can change it for example in the Sample from JSON (Flyleaf.UIConfig.json), I didn't included in the Settings form yet.

I think v2 was supporting stroke as well, don't really remember. Here what I've found from back then https://github.com/SuRGeoNix/Flyleaf/blob/release-v2.x/Flyleaf/MediaRenderer.cs#L763 if you want to check it out

**Comment by Brandon689** [comment]
Ah yes, I tried it in json file, works well. Maybe thickness of 2 is actually best. I think using DirectWrite is most optimal maybe and for WinForms but its very complex code for just subtitles.

**Pull request merged**
